export const SEARCH_DEPARTURES = "SEARCH_DEPARTURES";
export const SET_SORT_BY = "SET_SORT_BY";
export const SET_SEARCH_INITIATED = "SET_SEARCH_INITIATED";
export const SET_SEARCH_FINALISED = "SET_SEARCH_FINALISED";
